apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: deploy-staging.yaml
- path: svc-staging.yaml
- path: ingress-staging.yaml
namespace: app-staging
