name: CI/CD Pipeline

on:
  pull_request:
    types: 
      - closed
    paths-ignore:
      - 'VERSION'
    branches:
      - dev
  push:
    branches:
      - prod
      - dev
      - staging
    paths-ignore:
      - 'VERSION'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Determine version increment
        id: version-increment
        run: |
          commit_message=$(git log -1 --pretty=%B)
          if [[ "$commit_message" == *"major:"* ]]; then
            echo "increment=major" >> "$GITHUB_OUTPUT"
            echo "release=true" >> "$GITHUB_ENV"
          elif [[ "$commit_message" == "minor:"* ]]; then
            echo "increment=minor" >> "$GITHUB_OUTPUT"
            echo "release=true" >> "$GITHUB_ENV"
          elif [[ "$commit_message" == "patch:"* ]]; then
            echo "increment=patch" >> "$GITHUB_OUTPUT"
            echo "release=true" >> "$GITHUB_ENV"
          else
            echo "release=false" >> "$GITHUB_ENV"
          fi

      - name: Get current version
        id: get-version
        run: echo "version=$(cat VERSION)" >> "$GITHUB_OUTPUT"

      - name: Increment version
        id: increment-version
        run: echo "new_version=$(docker run --rm -v ${PWD}:/app treeder/bump ${{ steps.version-increment.outputs.increment }})" >> "$GITHUB_OUTPUT"
        if: | 
          github.ref == 'refs/heads/dev' &&
          env.release == 'true'

      - name: Update VERSION file
        run: echo "${{ steps.increment-version.outputs.new_version }}" > VERSION
        if: | 
          github.ref == 'refs/heads/dev' &&
          env.release == 'true'

      - name: Get updated version
        id: updated-version
        run: echo "version=$(cat VERSION)" >> "$GITHUB_OUTPUT"

      - uses: EndBug/add-and-commit@v9
        name: Commit VERSION file to Dev 
        with:
          add: 'VERSION'
          author_name: 'Afraz Ahmed'
          author_email: 'aphraz@live.com'
          fetch: false
          message: 'Updating VERSION file'
          pathspec_error_handling: ignore
          push: origin dev --force
          tag: "${{ steps.updated-version.outputs.version }} --force"
          tag_push: '--force'
        if: | 
          github.ref == 'refs/heads/dev' &&
          env.release == 'true'


      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build and Push Dev
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:${{ steps.updated-version.outputs.version }}-dev .
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:${{ steps.updated-version.outputs.version }}-dev
        if: | 
          github.ref == 'refs/heads/dev' &&
          env.release == 'false'
      
      - name: Docker Build and Push Dev-release
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:${{ steps.updated-version.outputs.version }}-dev .
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:${{ steps.updated-version.outputs.version }}-dev
        if: | 
          github.ref == 'refs/heads/dev' &&
          env.release == 'true'

      - name: Docker Build and Push Staging
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:${{ steps.updated-version.outputs.version }}-stag .
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:${{ steps.updated-version.outputs.version }}-stag
        if: github.ref == 'refs/heads/staging'

      - name: Docker Build and Push Prod
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:${{ steps.updated-version.outputs.version }}-prod .
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:${{ steps.updated-version.outputs.version }}-prod
        if: github.ref == 'refs/heads/prod'
      
      - name: Notify Slack - Release
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `Workflow: ${process.env.AS_WORKFLOW}\nJob: ${process.env.AS_JOB}\nCommit: ${process.env.AS_COMMIT}\nVersion: ${process.env.AS_VERSION}\nRepository: ${process.env.AS_REPO}@${process.env.AS_REF}\nAuthor: ${process.env.AS_AUTHOR}\nStatus: ${{ job.status }}\nDuration: ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          AS_VERSION: ${{ steps.updated-version.outputs.version }}
        if: | 
          github.ref == 'refs/heads/dev' &&
          env.release == 'true'

      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `Workflow: ${process.env.AS_WORKFLOW}\nJob: ${process.env.AS_JOB}\nCommit: ${process.env.AS_COMMIT}\nVersion: ${process.env.AS_VERSION}\nRepository: ${process.env.AS_REPO}@${process.env.AS_REF}\nAuthor: ${process.env.AS_AUTHOR}\nStatus: ${{ job.status }}\nDuration: ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          AS_VERSION: ${{ steps.updated-version.outputs.version }}
        if: env.release == 'false'
  
  infra:
    runs-on:
      ubuntu-latest
      
    env:
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      S3_REGION: ${{ secrets.S3_REGION }}
      DYNAMODB_TABLE: ${{ secrets.DYNAMODB_TABLE }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Terraform CLI Setup
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init 
        run: |
          cd terraform
          export ENVIRONMENT=$(echo "${{ github.ref }}" | sed -e "s/refs\/heads\///g")
          export TF_VAR_environment=$ENVIRONMENT
          terraform init \
            -backend-config="bucket=${S3_BUCKET}" \
            -backend-config="key=state/${ENVIRONMENT}-env.tfstate" \
            -backend-config="region=${S3_REGION}" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=${DYNAMODB_TABLE}"

      - name: Terraform Plan
        id: tf-plan
        run: |
          cd terraform
          export ENVIRONMENT=$(echo "${{ github.ref }}" | sed -e "s/refs\/heads\///g")
          export TF_VAR_environment=$ENVIRONMENT
          export exitcode=0
          terraform plan -detailed-exitcode -no-color  || export exitcode=$?

          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
        
          if [ $exitcode -eq 1 ]; then
            echo Terraform Plan Failed!
          exit 1
          else 
            exit 0
          fi
      - name: Terraform Apply
        run: |
          cd terraform
          export ENVIRONMENT=$(echo "${{ github.ref }}" | sed -e "s/refs\/heads\///g")
          export TF_VAR_environment=$ENVIRONMENT
          terraform apply -auto-approve
        if: ${{ steps.tf-plan.outputs.exitcode }} == 0
