name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
      - staging
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build and Push Dev
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:dev .
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:dev
        if: github.ref == 'refs/heads/dev'

      - name: Docker Build and Push Staging
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:stag .
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:stag
        if: github.ref == 'refs/heads/staging'

      - name: Docker Build and Push Prod
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:prod .
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:prod
        if: github.ref == 'refs/heads/main'
